# Generated by Django 5.0.6 on 2024-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id_ramo', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_ramo', models.CharField(max_length=20)),
                ('creditos', models.IntegerField(max_length=2)),
                ('escuela', models.CharField(max_length=20)),
            ],
        ),
    ]
