# Generated by Django 5.0.6 on 2024-05-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='creditos',
            field=models.IntegerField(),
        ),
    ]
